#lang racket
(require "interpreter.rkt")
(require "simpleParser.rkt")

(define run_tests
    (lambda ()
        (display (interpret "test_cases/test1")) (newline)
        (display (interpret "test_cases/test2")) (newline)
        (display (interpret "test_cases/test3")) (newline)
        (display (interpret "test_cases/test4")) (newline)
        (display (interpret "test_cases/test5")) (newline)
        (display (interpret "test_cases/test6")) (newline)
        (display (interpret "test_cases/test7")) (newline)
        (display (interpret "test_cases/test8")) (newline)
        (display (interpret "test_cases/test9")) (newline)
        (display (interpret "test_cases/test10")) (newline)
        ;;(display (interpret "test_cases/test11")) (newline)
        ;;(display (interpret "test_cases/test12")) (newline)
        ;;(display (interpret "test_cases/test13")) (newline)
        ;;(display (interpret "test_cases/test14")) (newline)
        (display (interpret "test_cases/test15")) (newline)
        (display (interpret "test_cases/test16")) (newline)
        (display (interpret "test_cases/test17")) (newline)
        (display (interpret "test_cases/test18")) (newline)
        (display (interpret "test_cases/test19")) (newline)
        (display (interpret "test_cases/test20")) (newline)
    )
)